### ISSUE TITLE
move to storybook org

### ISSUE THREAD

**Issue by ndelangen** [oslabs-beta/aesop-for-storybook#13]
Let's get move involved, and move this into the storybook org on github?

https://github.com/storybookjs

I think https://github.com/storybookjs/vs-code-plugin would be a great repo name? WDYT?

**Comment by ArloGui** [comment]
That sounds good! After discussing it with the team we think vs-code-extension might be a little more consistent with where to search for it and such. We could further discuss this when we meet? We'd love to take the next step on this. How would you like to proceed?

**Comment by ndelangen** [comment]
Let's meet on friday 9am as suggested in your email, that works really well with my schedule!

**Comment by ArloGui** [comment]
Alright, good to hear! Looking forward to it.
